### ISSUE TITLE
How to initialize mysql container when created on openshift 3.11?

### ISSUE THREAD

**Issue by imranrazakhan** [sclorg/mysql-container#270]
I want to set initial data on MySQL of container. As per doc they recommend following way but its not working

```
apiVersion: extensions/v1beta1
kind: Pod
metadata:
  name: mysql
spec:
  containers:
  - name: mysql
    image: mysql        
    ports:
      - containerPort: 3306
    volumeMounts:
      - name: mysql-initdb
        mountPath: /docker-entrypoint-initdb.d
  volumes:
    - name: mysql-initdb
      configMap:
        name: mysql-initdb-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  initdb.sql: |
..... script here ....
```
